---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app-service
  labels:
    author: purna
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-app
...
