---
apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
  labels:
    author: purna
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-app
...
