---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: purna
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    name: voting-app
...
